"""
Alembic migration environment — async-compatible with asyncpg.

Remediation: CR-1 (P0)
Replaces the `Base.metadata.create_all` bootstrap in init_db() with a
proper Alembic-managed schema lifecycle.

Architecture decisions:
  - Uses asyncpg/asyncio runner (run_async_migrations) for production
  - Falls back to sync runner for alembic CLI invoked without running loop
  - target_metadata wired to the ORM Base so all models are discoverable
  - DATABASE_URL read from environment (same source as src/config.py)
  - `compare_type=True` enables automatic detection of column type changes
  - `include_schemas=True` supports multi-schema deployments

Usage:
  # Apply all pending migrations
  alembic upgrade head

  # Generate new autogenerated migration
  alembic revision --autogenerate -m "add team_id to incidents"

  # Rollback last migration
  alembic downgrade -1

  # Show current revision
  alembic current
"""
from __future__ import annotations

import asyncio
import os
from logging.config import fileConfig

from sqlalchemy import pool
from sqlalchemy.engine import Connection
from sqlalchemy.ext.asyncio import async_engine_from_config

from alembic import context

# ── Import ORM metadata so Alembic can autogenerate diffs ─────────────────────
# CRITICAL: All ORM models must be imported here (or via their module)
# before alembic can detect them. Add new model imports below.
from src.incident_tracker import Base  # noqa: F401 — registers all ORM models

# ── Alembic Config object ─────────────────────────────────────────────────────
config = context.config

# Override sqlalchemy.url from environment variable — never hardcode credentials.
# Priority: DATABASE_URL env var > alembic.ini sqlalchemy.url setting
_db_url = os.environ.get("DATABASE_URL") or config.get_main_option("sqlalchemy.url")
if not _db_url:
    raise RuntimeError(
        "DATABASE_URL environment variable or alembic.ini sqlalchemy.url must be set. "
        "Example: export DATABASE_URL=postgresql+asyncpg://user:pass@localhost:5432/incidents"
    )
config.set_main_option("sqlalchemy.url", _db_url)

# ── Logging ────────────────────────────────────────────────────────────────────
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# ── Target metadata ────────────────────────────────────────────────────────────
target_metadata = Base.metadata


# ── Offline migrations (generates SQL script without a live DB) ───────────────
def run_migrations_offline() -> None:
    """
    Run migrations in 'offline' mode — generate SQL without a live DB connection.
    Useful for generating reviewed migration scripts for DBA-managed deployments.
    """
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        compare_type=True,
        include_schemas=True,
    )
    with context.begin_transaction():
        context.run_migrations()


# ── Online migrations (async, runs against live DB) ───────────────────────────
def do_run_migrations(connection: Connection) -> None:
    context.configure(
        connection=connection,
        target_metadata=target_metadata,
        compare_type=True,
        include_schemas=True,
    )
    with context.begin_transaction():
        context.run_migrations()


async def run_async_migrations() -> None:
    """Run migrations using an async engine (required for asyncpg)."""
    connectable = async_engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )
    async with connectable.connect() as connection:
        await connection.run_sync(do_run_migrations)
    await connectable.dispose()


def run_migrations_online() -> None:
    """Entry point for online migration mode — detects async vs sync context."""
    try:
        loop = asyncio.get_running_loop()
        # If a loop is already running (e.g., inside pytest-asyncio), schedule
        # migration as a task and wait for it.
        import concurrent.futures
        with concurrent.futures.ThreadPoolExecutor(max_workers=1) as pool_exec:
            future = pool_exec.submit(asyncio.run, run_async_migrations())
            future.result()
    except RuntimeError:
        # No running loop — safe to call asyncio.run() directly.
        asyncio.run(run_async_migrations())


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
