"""
ml_models/incident_anomaly/registry.py
=======================================
Model registry for the incident anomaly detector.

Responsibilities:
  - Load the serialized IsolationForest artifact from disk on first access
  - Expose version, health-check, and reload primitives
  - Thread-safe singleton via threading.Lock

Attribution:
    sklearn.ensemble.IsolationForest — BSD-3-Clause License
    Copyright (c) 2007-2025 The scikit-learn developers.
    See MODEL_CARD.md for full license text and BibTeX citation.

Remediation changelog:
  SEC-03  Fixed TOCTOU race in _ensure_loaded(): lock is now acquired
          before the None-check, not after. This is correct double-checked
          locking — one lock acquisition, one re-check inside the lock.
  SEC-04  Added SHA-256 hash verification of the artifact file before
          joblib.load(). Reads expected hash from a sidecar
          .sha256 manifest file (artifacts/isolation_forest_v1.joblib.sha256)
          if present; falls back to _EXPECTED_SHA256 constant; skips with
          WARNING if constant is the zero-sentinel (backward compat until
          MLOPS-01 training pipeline ships the manifest).
  SEC-05  health() no longer exposes the absolute artifact_path filesystem
          path. Replaced with artifact_file (basename) and artifact_version.
"""
from __future__ import annotations

import hashlib
import logging
import threading
import time
from pathlib import Path
from typing import Any

import joblib
import numpy as np
from sklearn.ensemble import IsolationForest

log = logging.getLogger(__name__)

_ARTIFACT_DIR = Path(__file__).parent / "artifacts"
_MODEL_FILE = _ARTIFACT_DIR / "isolation_forest_v1.joblib"
_MANIFEST_FILE = _ARTIFACT_DIR / "isolation_forest_v1.joblib.sha256"
MODEL_VERSION = "1.0.0"

# Decision boundary: scores below this threshold are flagged as anomalous.
_ANOMALY_THRESHOLD: float = 0.0

# SEC-04: Expected SHA-256 hex digest of the .joblib artifact.
# This constant is the fallback when no sidecar manifest file is present.
# The zero-sentinel (64 zeros) means "no pinned hash yet" — verification
# is skipped with a WARNING. Replace with the real digest once MLOPS-01
# (training pipeline) commits the .sha256 manifest alongside the artifact.
_EXPECTED_SHA256: str = "0" * 64  # sentinel — replace with real digest


def _load_expected_hash() -> str | None:
    """Return the expected SHA-256 hex string, or None if unverifiable."""
    # Prefer the sidecar manifest (generated by training pipeline).
    if _MANIFEST_FILE.exists():
        raw = _MANIFEST_FILE.read_text().strip().split()[0]
        if len(raw) == 64:
            return raw
        log.warning("registry.manifest_malformed", extra={"path": str(_MANIFEST_FILE)})

    # Fall back to the embedded constant.
    if _EXPECTED_SHA256 == "0" * 64:
        log.warning(
            "registry.hash_check_skipped",
            extra={
                "reason": "_EXPECTED_SHA256 is zero-sentinel; pin a real digest or ship a .sha256 manifest",
                "artifact": _MODEL_FILE.name,
            },
        )
        return None
    return _EXPECTED_SHA256


def _verify_artifact_hash(path: Path) -> None:
    """Compute SHA-256 of *path* and compare against the expected digest.

    Raises:
        RuntimeError: if the digest does not match the expected value.
    """
    expected = _load_expected_hash()
    if expected is None:
        return  # skip — no hash available yet (backward compat)

    sha = hashlib.sha256()
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(65_536), b""):
            sha.update(chunk)
    actual = sha.hexdigest()

    if actual != expected:
        raise RuntimeError(
            f"Artifact hash mismatch for {path.name}. "
            f"Expected {expected!r}, got {actual!r}. "
            "The model file may have been tampered with or corrupted. "
            "Re-run the training pipeline to regenerate a verified artifact."
        )
    log.info("registry.artifact_hash_verified", extra={"artifact": path.name, "sha256": actual[:16] + "..."})


class ModelRegistry:
    """Thread-safe lazy loader for the incident anomaly model."""

    def __init__(self) -> None:
        self._model: IsolationForest | None = None
        self._lock = threading.Lock()
        self._loaded_at: float | None = None

    def load(self) -> None:
        """Explicitly load or reload the model artifact from disk.

        Acquires the lock for the full duration of hash verification +
        deserialization to prevent concurrent loads (SEC-03).
        """
        with self._lock:
            # SEC-04: Verify hash before deserializing (arbitrary code exec risk).
            _verify_artifact_hash(_MODEL_FILE)
            self._model = joblib.load(_MODEL_FILE)
            self._loaded_at = time.time()

    def _ensure_loaded(self) -> IsolationForest:
        # SEC-03: Correct double-checked locking.
        # Acquire the lock FIRST, then re-check. This eliminates the TOCTOU
        # window where two threads both observe self._model is None before
        # either acquires the lock.
        if self._model is not None:
            return self._model  # fast path — no lock needed once loaded
        with self._lock:
            if self._model is None:  # re-check inside lock
                _verify_artifact_hash(_MODEL_FILE)
                self._model = joblib.load(_MODEL_FILE)
                self._loaded_at = time.time()
        assert self._model is not None  # noqa: S101 — internal guard
        return self._model

    def predict(self, features: list[float]) -> dict[str, Any]:
        """Run inference on a single feature vector.

        Args:
            features: Ordered list of 7 floats matching the training schema.
                      Order: [severity_numeric, alert_count,
                              time_to_detect_minutes, affected_services,
                              on_call_escalations, duplicate_alert_ratio,
                              blast_radius_pct]

        Returns:
            dict with keys: anomaly_score, is_anomalous, confidence,
            inference_latency_ms.
        """
        model = self._ensure_loaded()
        x = np.array(features, dtype=np.float64).reshape(1, -1)

        t0 = time.perf_counter()
        score: float = float(model.decision_function(x)[0])
        latency_ms = (time.perf_counter() - t0) * 1_000

        is_anomalous = score < _ANOMALY_THRESHOLD
        raw_confidence = 1.0 / (1.0 + np.exp(score * 3))  # sigmoid-ish
        confidence = float(np.clip(raw_confidence, 0.0, 1.0))

        return {
            "anomaly_score": round(score, 6),
            "is_anomalous": is_anomalous,
            "confidence": round(confidence, 6),
            "inference_latency_ms": round(latency_ms, 3),
        }

    def health(self) -> dict[str, Any]:
        """Return a health summary for use by the /ready endpoint.

        SEC-05: Does NOT expose the absolute filesystem path of the artifact.
        Callers receive only the filename and version — no container internals.
        """
        loaded = self._model is not None
        return {
            "model_loaded": loaded,
            "model_version": MODEL_VERSION,
            "artifact_file": _MODEL_FILE.name,   # basename only — no path leak
            "artifact_exists": _MODEL_FILE.exists(),
            "loaded_at": self._loaded_at,
        }


# Module-level singleton — imported by the FastAPI router.
model_registry = ModelRegistry()
