#!/usr/bin/env bash
# scripts/generate_dev_keys.sh
#
# Generates a local RSA-2048 dev keypair using jwt_rs256.generate_dev_keypair()
# and writes the keys to .env (or a target file).
#
# !! WARNING: DEV KEYS ONLY !!
# Keys generated by this script are for LOCAL DEVELOPMENT ONLY.
# Do NOT use these keys in staging or production environments.
# For production, use a secrets manager (AWS Secrets Manager, GCP Secret Manager,
# Vault, or Kubernetes Secrets) to provision and rotate RSA keypairs.
#
# Usage:
#   ./scripts/generate_dev_keys.sh              # writes to .env
#   ./scripts/generate_dev_keys.sh .env.local   # writes to a specific file
#   DRY_RUN=1 ./scripts/generate_dev_keys.sh   # print keys, do not write

set -euo pipefail

TARGET_FILE="${1:-.env}"
DRY_RUN="${DRY_RUN:-0}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

# ── Colour output ────────────────────────────────────────────────────────────
RED='\033[0;31m'
YELLOW='\033[1;33m'
GREEN='\033[0;32m'
NC='\033[0m'

warn()  { echo -e "${YELLOW}[WARN]${NC}  $*" >&2; }
error() { echo -e "${RED}[ERROR]${NC} $*" >&2; }
ok()    { echo -e "${GREEN}[OK]${NC}    $*"; }

# ── Safety guard ─────────────────────────────────────────────────────────────
if [[ "${ENVIRONMENT:-development}" == "production" ]]; then
  error "ENVIRONMENT=production detected. Refusing to generate dev keys."
  error "Provision production keys via your secrets manager."
  exit 1
fi

# ── Check Python environment ──────────────────────────────────────────────────
if ! python3 -c "import sys; sys.exit(0 if sys.version_info >= (3, 11) else 1)" 2>/dev/null; then
  error "Python 3.11+ required. Found: $(python3 --version 2>&1)"
  exit 1
fi

if ! python3 -c "from src.auth.jwt_rs256 import generate_dev_keypair" 2>/dev/null; then
  error "Cannot import src.auth.jwt_rs256. Run this script from the repo root."
  error "  cd ${REPO_ROOT} && ./scripts/generate_dev_keys.sh"
  exit 1
fi

# ── Generate keypair ──────────────────────────────────────────────────────────
echo ""
warn "======================================================"
warn "  GENERATING DEV KEYS — FOR LOCAL USE ONLY"
warn "  Never commit these keys or use them in production."
warn "======================================================"
echo ""

KEYPAIR_JSON=$(python3 - <<'PYEOF'
import json, sys
sys.path.insert(0, ".")
from src.auth.jwt_rs256 import generate_dev_keypair
priv, pub, kid = generate_dev_keypair()
print(json.dumps({"private_key": priv, "public_key": pub, "key_id": kid}))
PYEOF
)

PRIVATE_KEY=$(echo "${KEYPAIR_JSON}" | python3 -c "import json,sys; d=json.load(sys.stdin); print(d['private_key'])")
PUBLIC_KEY=$(echo "${KEYPAIR_JSON}"  | python3 -c "import json,sys; d=json.load(sys.stdin); print(d['public_key'])")
KEY_ID=$(echo "${KEYPAIR_JSON}"      | python3 -c "import json,sys; d=json.load(sys.stdin); print(d['key_id'])")

if [[ "${DRY_RUN}" == "1" ]]; then
  echo "# ── DRY RUN — keys not written ──────────────────────"
  echo "RSA_PRIVATE_KEY_PEM=${PRIVATE_KEY}"
  echo "RSA_PUBLIC_KEY_PEM=${PUBLIC_KEY}"
  echo "JWT_KEY_ID=${KEY_ID}"
  echo "# ── END DRY RUN ──────────────────────────────────────"
  ok "Dry run complete. No files modified."
  exit 0
fi

# ── Write or update .env ──────────────────────────────────────────────────────
ABS_TARGET="${REPO_ROOT}/${TARGET_FILE}"

# Back up existing file if it exists
if [[ -f "${ABS_TARGET}" ]]; then
  BACKUP="${ABS_TARGET}.bak.$(date +%Y%m%d_%H%M%S)"
  cp "${ABS_TARGET}" "${BACKUP}"
  warn "Existing ${TARGET_FILE} backed up to ${BACKUP##*/}"
fi

# Remove any existing key entries, then append new ones
if [[ -f "${ABS_TARGET}" ]]; then
  # Strip old key lines (preserve all other env vars)
  TMPFILE=$(mktemp)
  grep -v -E '^(RSA_PRIVATE_KEY_PEM|RSA_PUBLIC_KEY_PEM|JWT_KEY_ID)=' "${ABS_TARGET}" > "${TMPFILE}" || true
  mv "${TMPFILE}" "${ABS_TARGET}"
fi

# Append new keys as single-line PEM (newlines replaced with \n literal)
PRIV_ONELINE=$(echo "${PRIVATE_KEY}" | tr '\n' '\\' | sed 's/\\/\\n/g' | sed 's/\\n$//g')
PUB_ONELINE=$(echo "${PUBLIC_KEY}"   | tr '\n' '\\' | sed 's/\\/\\n/g' | sed 's/\\n$//g')

cat >> "${ABS_TARGET}" <<EOF

# ── RSA Dev Keys (generated $(date -u +"%Y-%m-%dT%H:%M:%SZ")) ──
# DEV ONLY — do not commit or use in production
RSA_PRIVATE_KEY_PEM=${PRIV_ONELINE}
RSA_PUBLIC_KEY_PEM=${PUB_ONELINE}
JWT_KEY_ID=${KEY_ID}
EOF

ok "Dev keys written to ${TARGET_FILE}"
ok "Key ID: ${KEY_ID}"
echo ""
warn "Remember: add ${TARGET_FILE} to .gitignore if not already present."
